---
- name: Copy website tarball
  copy:
    src: website.tar.gz
    dest: /tmp/website.tar.gz

- name: Extract website to nginx root
  unarchive:
    src: /tmp/website.tar.gz
    dest: /var/www/html/
    remote_src: yes
    